[server]
maxUploadSize = 10000 
maxMessageSize = 1500
port=8501
runOnSave = false

[global]
developmentMode = false

[theme]
primaryColor="#d33682"
backgroundColor="#002b36"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"
font="sans serif"

[client]
showSidebarNavigation = false
